# Generated by Django 2.1.5 on 2019-02-18 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190218_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ost',
            new_name='post',
        ),
    ]
