# Generated by Django 2.1.5 on 2019-02-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='proce',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
