# Generated by Django 2.1.5 on 2019-02-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_proce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='proce',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
